<?php

namespace portalium\content\components;

use Yii;
use yii\base\BaseObject;

use portalium\content\models\Content;


class TriggerActions extends BaseObject
{
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }

    public function onUserDeleteBefore($event)
    {
        ['id' => $id_user, 'default_user' => $defaultUser, 'action' => $action] = $event->payload;
        if ($action == 'delete') {
            $contents = Content::find()->where(['id_user' => $id_user])->all();
            foreach ($contents as $content) {
                $content->delete();
            }
            

        }elseif($action == 'transfer'){
            if ($defaultUser) {
                $contents = Content::find()->where(['id_user' => $id_user])->all();
                foreach ($contents as $content) {
                    $content->id_user = $defaultUser;
                    $content->save();
                }
            }
        }

    }
}